from __future__ import annotations

from typing import Literal

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


# =============================================================================
# Retrieved Context
# =============================================================================

class RetrievedChunk(BaseModel):
    """
    A single retrieved knowledge chunk.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    company: str = Field(
        description="Knowledge base source."
    )

    product_area: str = Field(
        description="Product area associated with this document."
    )

    title: str = Field(
        description="Document title."
    )

    section: str = Field(
        description="Section title."
    )

    url: str = Field(
        description="Documentation URL."
    )

    text: str = Field(
        description="Retrieved document content."
    )

# =============================================================================
# Support Ticket
# =============================================================================

class SupportTicket(BaseModel):
    """
    Customer support ticket.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    issue: str = Field(
        min_length=1,
        description="Customer issue description."
    )

    subject: str = Field(
        default="",
        description="Optional ticket subject."
    )

    company: str = Field(
        default="",
        description="Company name."
    )
# =============================================================================
# Structured LLM Response
# =============================================================================

class SupportResponse(BaseModel):
    """
    Final structured response generated by the LLM.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    request_type: Literal[
        "product_issue",
        "feature_request",
        "bug",
        "invalid",
    ] = Field(
        description="Support request classification."
    )

    product_area: str = Field(
        description="Most relevant product area."
    )

    status: Literal[
        "Replied",
        "Escalated",
    ] = Field(
        description="Whether the issue was answered or escalated."
    )

    response: str = Field(
        description="Customer-facing support response."
    )

    justification: str = Field(
        description="Short evidence-based explanation."
    )


# =============================================================================
# Source Information
# =============================================================================

class SourceDocument(BaseModel):
    """
    Documentation source used to generate the response.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    company: str

    title: str

    url: str


# =============================================================================
# Public Agent Response
# =============================================================================

class AgentResponse(BaseModel):

    model_config = ConfigDict(
        extra="forbid"
    )

    response: SupportResponse

    sources: list[SourceDocument] = Field(
        default_factory=list
    )

    # NEW
    retrieved_context: list[str] = Field(
        default_factory=list,
        description="Retrieved document text used to generate the answer."
    )

    num_chunks: int = Field(
        default=0
    )

    token_estimate: int = Field(
        default=0
    )