from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from typing import Literal, Optional

# =============================================================================
# Retrieved Context
# =============================================================================

class RetrievedChunk(BaseModel):
    """
    A single retrieved knowledge chunk.
    """

    model_config = ConfigDict(extra="forbid")
    company: str = Field(description="Knowledge base source.")
    product_area: str = Field(description="Product area associated with this document.")
    title: str = Field(description="Document title.")
    section: str = Field(description="Section title.")
    url: str = Field(description="Documentation URL.")
    document_id: str = Field(description="Unique document identifier.")
    chunk_id: str = Field(description="Unique chunk identifier.")
    score: float = Field(description="Retrieval score.")
    text: str = Field(description="Retrieved document content.")

# =============================================================================
# Support Ticket
# =============================================================================

class SupportTicket(BaseModel):
    """
    Customer support ticket.
    """

    model_config = ConfigDict(extra="forbid")

    issue: str = Field(min_length=1, description="Customer issue description.")
    subject: str = Field(default="",description="Optional ticket subject.")
    company: str = Field(default="",description="Company name.")
    reranker: str = "none"
    search_mode: str = "hybrid"
# =============================================================================
# Structured LLM Response
# =============================================================================

class SupportResponse(BaseModel):
    """
    Final structured response generated by the LLM.
    """

    model_config = ConfigDict(extra="forbid")

    request_type: Literal["product_issue","feature_request","bug","invalid"] = Field(description="Support request classification.")
    product_area: str = Field(description="Most relevant product area.")
    status: Literal["Replied","Escalated"] = Field(description="Whether the issue was answered or escalated.")
    response: str = Field(description="Customer-facing support response.")
    justification: str = Field(description="Short evidence-based explanation.")


# =============================================================================
# Source Information
# =============================================================================

class SourceDocument(BaseModel):
    """
    Documentation source used to generate the response.
    """

    model_config = ConfigDict(extra="forbid")

    company: str
    title: str
    url: str

# =============================================================================
# Public Agent Response
# =============================================================================

class AgentResponse(BaseModel):

    model_config = ConfigDict(extra="forbid")

    response: SupportResponse
    sources: list[SourceDocument] = Field(default_factory=list)
    retrieved_context: list[str] = Field(default_factory=list,description="Retrieved document text used to generate the answer.")
    retrieved_chunks: list[RetrievedChunk] = Field(default_factory=list, description="Retrieved chunks with metadata.")
    num_chunks: int = Field(default=0)
    token_estimate: int = Field(default=0)
    retrieval_trace: dict = Field(default_factory=dict, description="Metadata trace about retrieval execution steps.")

    # Decision Gate fields (NEW)
    retrieval_required: bool = Field(default=True,description="Whether documentation retrieval was performed.")
    normalized_issue: str = Field(default="",description="Normalized description of the customer issue.")
    normalized_subject: str = Field(default="",description="Normalized subject of the ticket.")
    routing_reason: str = Field(default="",description="Justification for skipping or running retrieval.")
    confidence: float = Field(default=1.0,description="Confidence score of the routing decision.")
    selected_company: str = Field(default="", description="The selected company name.")
    detected_company: str = Field(default="", description="The inferred company name.")
    verified_company: str = Field(default="", description="The verified company name used for retrieval.")
    company_match: bool = Field(default=True, description="Whether selected_company matches detected_company.")
    company_confidence: float = Field(default=1.0, description="Company detection confidence score.")
    classification_confidence: float = Field(default=1.0, description="Routing decision confidence score.")

    # Token usage captured from LangChain usage_metadata for billing
    decision_input_tokens: int = Field(default=0,description="Input tokens consumed by the Decision Gate LLM call.")
    decision_output_tokens: int = Field(default=0, description="Output tokens generated by the Decision Gate LLM call.")
    generation_input_tokens: int = Field(default=0, description="Input tokens consumed by the Generation LLM call.")
    generation_output_tokens: int = Field(default=0, description="Output tokens generated by the Generation LLM call.")

